### ISSUE TITLE
Nothing happens when i press "Push me!"

### ISSUE THREAD

**Issue by maephisto** [houssem-yahiaoui/progressive-web-app-starter-kit#1]
I cloned the repo and gave it a go, but whenever I press "push me", nothing happens - in the console line i can se "sending push" but in the server logs nothings shows.

I also don't see any log output from the socket.io connection - could this be the issue?
The same behaviour i experienced on your demo page (on heroku)
Any idea what's wrong?

I use newest Chrome and Firefox, on OSX.

Thanks!

**Comment by houssem-yahiaoui** [comment]
Hi @maephisto, i'm using the same set of tools but over windows, in my setup i tested with Chrome and nothing showed up, it's weird enough because it's used to be working, but over mozilla thing everything is okey, i do believe that it's due to the fact that Chrome didn't fully implemented the web push as it should, but it's not the case over Mozilla ! please test again this time prefixing the website with a https:// prefix and tell if you're witnessing the subscription and the public/secret keys.

**Comment by houssem-yahiaoui** [comment]
Hey again, I found out that Chrome now expect the notification to those from firebase instead of the gcm. I've updated the repo adviced to check back.
